version: '3.6'

services:
   terraform:
    container_name: terraform
    image: hashicorp/terraform:0.15.5
    env_file:
      - .env
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true
